apiVersion: v2
name: pythia
description: Open-source Slack bot that connects an LLM to arbitrary MCP servers
type: application
version: 0.0.1
appVersion: "0.0.1"
home: https://github.com/SixTwoDev/Pythia
sources:
  - https://github.com/SixTwoDev/Pythia
